### PR TITLE
Added renovate config.

### PR DESCRIPTION
**Pull request by Chinwendu20**
This would ensure the project  is up to date with the opentelemetry API as well as other packages that it depends on.

Fixes https://github.com/kubearmor/otel-adapter/issues/4

### CODE REVIEW

**Review by DelusionalOptimist — COMMENTED** [review]
@Chinwendu20 For kubearmor and kubearmor-client repos we are using renovate bot which takes care of even Pseudo-version updates. We do it so that repositories get faster updates of packages like `kubearmor/protobuf` and we don't have to hold off until a tagged release of KubeArmor.
Should we use renovate here as well? :thinking:

**Comment by Chinwendu20** [comment]
Yes, I think we should. When I read about setting it up, it involves adding the renovate app to the repo. As a member of this org, do you mind doing this, please?

**Comment by DelusionalOptimist** [comment]
Hey @Chinwendu20 we have renovate bot added org wide. We just need to add a config.
See this for ref - https://github.com/kubearmor/KubeArmor/pull/1209

**Comment by Chinwendu20** [comment]
Thanks @DelusionalOptimist updated.

**Pull request merged**
