### PR TITLE
updated CI

### PR DESCRIPTION
**Pull request by Chinwendu20**
Currently the conditional for the CI test does not match the correct the correct repo name, this fixes that and also removes the conditional for the CI test. We only need it when pushing to docker repo.

### CODE REVIEW

**Comment by Chinwendu20** [comment]
@DelusionalOptimist do you mind looking at this, so we rerun the CI and update the repo

**Review by DelusionalOptimist — COMMENTED** [review]
Thanks for the PR @Chinwendu20! Would've never noticed if you didn't create this. 🙌

These changes look good. I think we should also change other instances of `otel-receiver` likewise. What do you say? This will help us avoid confusion by keeping the go modules and docker image consistent with the repo name.

**Comment by DelusionalOptimist** [comment]
Hey @Chinwendu20... I updated some other refs by myself so that further work can be done on this... hope you don't mind. : )

**Comment by Chinwendu20** [comment]
Fine by me! So sorry that I abandoned it

**Review by DelusionalOptimist — APPROVED** [review]

**Comment by DelusionalOptimist** [comment]
> Fine by me! So sorry that I abandoned it

No worries! We all get busy :sweat_smile:

**Pull request merged**
